unique_ids:
  assets:
    standard-page.html: KWI66C6AOQAIQ4CT2MYSC4SVZ67FNJUJ
    theme.css: J2CUY4YQ6PUVSHVI7QPS2VP7P7LPFD2I
  forms:
    game_frm: '1745985794261331310125342.5078'
    player_frm: RMTTEMQW5CXQADBU2ND4ITXXCTI3BJMY
  modules: {}
  scripts: {}
  server_modules: {}
